import { Injectable } from '@angular/core'

import { Shot } from './shot.model'

@Injectable({
    providedIn: 'root'
})
export class ShotsService {
    private _shots: Shot[] = [
        new Shot(
            's1',
            'Columbico Bird Food - branding & packaging',
            'Branding',
            'Graphic Design',
            'Illustration',
            'Columbico',
            'Logo',
            'Packaging',
            'Bird Food',
            'Colors',
            'Drawing',
            './assets/img/shots/s1.jpg',
            'c1',
            'Milica Tucakovic'
        ),
        new Shot(
            's2',
            'RENUKA BREWERY - branding & packaging',
            'Branding',
            'Graphic Design',
            'Illustration',
            'Renuka',
            'Logo',
            'Packaging',
            'Brewery',
            'Bottles',
            'Beer',
            './assets/img/shots/s2.jpg',
            'c1',
            'Milica Tucakovic'
        ),
        new Shot(
            's3',
            'BOOK DESIGN, 01',
            'Graphic Design',
            'Illustration',
            'Typography',
            'San Smesnog Soveka',
            'Book',
            'Editorial',
            'Collage',
            'Typo',
            'Images',
            './assets/img/shots/s3.jpg',
            'c1',
            'Milica Tucakovic'
        ),
        new Shot(
            's4',
            'POSTER DESIGN, 01',
            'Graphic Design',
            'Illustration',
            'Typography',
            'Dostojevski',
            'Collage',
            'Poster',
            'Print',
            'Typo',
            'Abstract',
            './assets/img/shots/s4.jpg',
            'c1',
            'Milica Tucakovic'
        ),
        new Shot(
            's5',
            'Bleaching Vol. 2',
            'Graphic Design',
            'Photography',
            'Photography',
            'Photos',
            'Beach',
            'Abstract',
            'Vague',
            'bleaching',
            'Greyscale',
            './assets/img/shots/s5.jpg',
            'c1',
            'Milica Tucakovic'
        ),
        new Shot(
            's6',
            'WideCap',
            'Motion',
            'Graphic Design',
            'Illustration',
            'WideCap',
            'Streets',
            'Illustration',
            'Video',
            'Audio',
            'After Effects',
            './assets/img/shots/s6.jpg',
            'c2',
            'Tomek Bilic'
        ),
        new Shot(
            's7',
            'Boehringer Ingelheim: STEM',
            'Motion',
            'Graphic Design',
            '3D Modeling',
            'Question',
            'Boehringer Ingelheim',
            'STEM',
            'Orange',
            '3D',
            'Video',
            './assets/img/shots/s7.jpg',
            'c2',
            'Tomek Bilic'
        ),
        new Shot(
            's8',
            'Onde Render A Day - Month #1',
            'Motion',
            'Graphic Design',
            'Illustration',
            'Renders',
            'Illustartions',
            'Abstract',
            'Colors',
            'Random stuf',
            'Monthly',
            './assets/img/shots/s8.jpg',
            'c2',
            'Tomek Bilic'
        ),
        new Shot(
            's9',
            'Infinite Jam',
            'Motion',
            'Graphic Design',
            'Illustration',
            'Infinite Jam',
            'Auto',
            'Video',
            'Red',
            'Person',
            'Motion',
            './assets/img/shots/s9.jpg',
            'c2',
            'Tomek Bilic'
        ),
        new Shot(
            's10',
            'Reserva: Versatility',
            'Motion',
            'Graphic Design',
            'Illustration',
            'Reserva',
            'Versatility',
            'Shoes',
            'Video',
            'Colorful',
            'Shapes',
            './assets/img/shots/s10.jpg',
            'c2',
            'Tomek Bilic'
        ),
        new Shot(
            's11',
            'Tmall New Interpretation of Traditional Solar Terms',
            'Branding',
            'Graphic Design',
            'Illustration',
            'Packaging',
            'Chinese',
            'Asian',
            'Tmall',
            'Traditional Solar Terms',
            'Logo',
            './assets/img/shots/s11.jpg',
            'c3',
            'Anna Zhou'
        ),
        new Shot(
            's12',
            'SandBox Immersive Festival Opening Video',
            'Motion',
            'Graphic Design',
            'Typography',
            'SandBox',
            'festival',
            'Video',
            'Audio',
            'Meeting',
            'Colorful',
            './assets/img/shots/s12.jpg',
            'c3',
            'Anna Zhou'
        ),
        new Shot(
            's13',
            'Wall paintings for LxU Studio',
            'Branding',
            'Graphic Design',
            'Illustration',
            'Paintings',
            'Collage',
            'LxU Studio',
            'Abstract',
            'Sober',
            'Agency',
            './assets/img/shots/s13.jpg',
            'c3',
            'Anna Zhou'
        ),
        new Shot(
            's14',
            'New Balance Fuel Running Battle',
            'Branding',
            'Graphic Design',
            'Illustration',
            'New Balance',
            'Shoes',
            'Fuel',
            'Campaign',
            'Corporate Design',
            'Brand',
            './assets/img/shots/s14.jpg',
            'c3',
            'Anna Zhou'
        ),
        new Shot(
            's15',
            'PEACEBIRD × LxU New Year Gift Box',
            'Branding',
            'Graphic Design',
            'Illustration',
            'Packaging',
            'Gift Box',
            'LxU Studio',
            'Agency',
            'New Year',
            'Chinese',
            './assets/img/shots/s15.jpg',
            'c3',
            'Anna Zhou'
        ),
        new Shot(
            's16',
            'South Bank Tower',
            'Branding',
            'Graphic Design',
            'Illustration',
            'South Bank',
            'Tower',
            'London',
            'Housing',
            'Luxury',
            'Advertisement',
            './assets/img/shots/s16.jpg',
            'c4',
            "Jacqueline L' Herminez"
        ),
        new Shot(
            's17',
            'Animated Clip Concept',
            'Motion',
            'Graphic Design',
            'Illustration',
            'Animated',
            'Video',
            'Drawings',
            'After Effects',
            'Concept',
            'Visualisation',
            './assets/img/shots/s17.jpg',
            'c4',
            "Jacqueline L' Herminez"
        ),
        new Shot(
            's18',
            'Stanley Park Brewing',
            'Branding',
            'Graphic Design',
            'Illustration',
            'Brewery',
            'Beer',
            'Packaging',
            'Blue Tones',
            'Different Seasons',
            'Different Beers',
            './assets/img/shots/s18.jpg',
            'c4',
            "Jacqueline L' Herminez"
        ),
        new Shot(
            's19',
            '2001 a Space Odyssey screen print',
            'Graphic Design',
            'Illustration',
            'Typography',
            'Movie',
            'Space Odyssey',
            'Print',
            'Poster',
            'Kubrick',
            'Classic',
            './assets/img/shots/s19.jpg',
            'c4',
            "Jacqueline L' Herminez"
        ),
        new Shot(
            's20',
            'Air France magazine',
            'Branding',
            'Graphic Design',
            'Illustration',
            'Air France',
            'Magazine',
            'Airlines',
            'Corporate',
            'French',
            'Holiday',
            './assets/img/shots/s20.jpg',
            'c4',
            "Jacqueline L' Herminez"
        ),
        new Shot(
            's21',
            'UX UI / Collection / Vol. II',
            'Typography',
            'UX / UI Design',
            'Web Design',
            'Interface',
            'Application',
            'Website',
            'Collection',
            'Interaction',
            'Grid',
            './assets/img/shots/s21.jpg',
            'c5',
            'Viktor Vaugn'
        ),
        new Shot(
            's22',
            'UX UI Project / Nap App',
            'Branding',
            'UX / UI Design',
            'Web Design',
            'Nap App',
            'Application',
            'Typo',
            'Concept',
            'Icons',
            'Health',
            './assets/img/shots/s22.jpg',
            'c5',
            'Viktor Vaugn'
        ),
        new Shot(
            's23',
            'Soda Stereo',
            'Branding',
            'Graphic Design',
            'Illustration',
            'Soda Stereo',
            'Logo',
            'Packaging',
            'Drawings',
            'Visual Identity',
            'Concept',
            './assets/img/shots/s23.jpg',
            'c5',
            'Viktor Vaugn'
        ),
        new Shot(
            's24',
            'Ataque de Pánico / Campaña Social',
            'Branding',
            'Graphic Design',
            'Illustration',
            'brochure',
            'Poster',
            'Application',
            'Website',
            'Visual Identity',
            'Concept',
            './assets/img/shots/s24.jpg',
            'c5',
            'Viktor Vaugn'
        ),
        new Shot(
            's25',
            'UX UI / Collection / Vol. I',
            'Typography',
            'UX / UI Design',
            'Web Design',
            'Interface',
            'Application',
            'Website',
            'Collection',
            'Interaction',
            'Grid',
            './assets/img/shots/s25.jpg',
            'c5',
            'Viktor Vaugn'
        ),
        new Shot(
            's26',
            'SOLO SOCIETY',
            'Branding',
            'Graphic Design',
            'Typography',
            'Solo Society',
            'Print',
            'Poster',
            'Book',
            'Magazine',
            'Typo',
            './assets/img/shots/s26.jpg',
            'c6',
            'Nicholas Craven'
        ),
        new Shot(
            's27',
            '36daysoftype 2019',
            'Graphic Design',
            'Illustration',
            'Typography',
            'Collection',
            'Collage',
            'Typo',
            'Print',
            'Minimal',
            'Abstract',
            './assets/img/shots/s27.jpg',
            'c6',
            'Nicholas Craven'
        ),
        new Shot(
            's28',
            'Legendos magazine',
            'Branding',
            'Graphic Design',
            'Typography',
            'Print',
            'Magazine',
            'Editorial',
            'Typo',
            'Minimal',
            'White Space',
            './assets/img/shots/s28.jpg',
            'c6',
            'Nicholas Craven'
        ),
        new Shot(
            's29',
            'SOMFHHB Type Posters',
            'Branding',
            'Graphic Design',
            'Typography',
            'SOMFHHB',
            'Print',
            'Posters',
            'Typo',
            'Colorful',
            'Swiss Style',
            './assets/img/shots/s29.jpg',
            'c6',
            'Nicholas Craven'
        ),
        new Shot(
            's30',
            'CIURLIONIS',
            'Graphic Design',
            'Photography',
            'Typography',
            'Print',
            'Editorial',
            'Minimal',
            'White Space',
            'Typo',
            'Magazine',
            './assets/img/shots/s30.jpg',
            'c6',
            'Nicholas Craven'
        )
    ]

    get shots() {
        return [...this._shots]
    }

    constructor() {}

    getShot(id: string) {
        return { ...this._shots.find(s => s.id === id) }
    }
}
